/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.krysalis.barcode4j.impl.code128.Code128Bean;

import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;

/**
 *
 * @author SHADOW
 */
public class main extends javax.swing.JFrame {

    private String path;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        path=load_param();
        //pg.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new Gpanl();
        jPanel3 = new javax.swing.JPanel();
        nbr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pg = new javax.swing.JProgressBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Code3 = new javax.swing.JTextField();
        Prix = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        type_d = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        code2 = new javax.swing.JTextField();
        code1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        type_c = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codebar generateur");
        setBackground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Generer pdf", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nbr.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10" }));
        nbr.setToolTipText("Image format");
        jPanel3.add(nbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("element par line");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, 30));

        check.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        check.setText("Crée");
        jPanel3.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 40, 70, -1));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Parcourir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Crée un Pdf de ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Crée un Pdf apartir d,une image");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 450, 140));

        pg.setBackground(new java.awt.Color(204, 255, 204));
        pg.setForeground(new java.awt.Color(51, 51, 255));
        pg.setStringPainted(true);
        jPanel4.add(pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 530, 20));

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        code.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        code.setToolTipText("Entrer le code");
        jPanel5.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Codebar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 30));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setText("CodeRQ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 100, 30));

        jTabbedPane1.addTab("Code bar Simple", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Code3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Code3.setToolTipText("Code");
        jPanel6.add(Code3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 30));

        Prix.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Prix.setToolTipText("Prix");
        jPanel6.add(Prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 390, 30));

        Nom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Nom.setToolTipText("Nom");
        jPanel6.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 390, 30));

        type_d.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        type_d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code bar", "code RQ" }));
        jPanel6.add(type_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, 30));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText("Génere");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 30));

        jTabbedPane1.addTab("Code bar avec description", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        code2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        code2.setToolTipText("Entrer le code");
        jPanel7.add(code2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 390, 30));

        code1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        code1.setToolTipText("Entrer le code");
        jPanel7.add(code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 390, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Type");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 50, 30));

        type.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chifre", "Letre", "Mix" }));
        type.setToolTipText("Image format");
        jPanel7.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Code");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 50, 30));

        type_c.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        type_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar", "RQ" }));
        type_c.setToolTipText("Image format");
        jPanel7.add(type_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 80, 30));

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton5.setText("Suit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, 30));

        jTabbedPane1.addTab("Plusieur Code", jPanel7);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 490, 280));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 530));

        jMenu1.setText("Quiter");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ouvrir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(547, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!code.getText().equals("")) {
            pg.setValue(1);
            generateQRCode(code.getText(), 200, 200, path+"/RQ"+code.getText()+".png");
            if (check.isSelected()) generate_pdf(path+"/RQ"+code.getText()+".png");
            pg.setValue(100);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!code.getText().equals("")) {
            pg.setValue(1);
            codebar(code.getText());
            if (check.isSelected()) generate_pdf(path+"/B"+code.getText()+".png");
            pg.setValue(100);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if((!code2.getText().equals("")) && (!code1.getText().equals("")) && (!code1.getText().equals(code2.getText())) && (code2.getText().length()==code1.getText().length())) {
            pg.setValue(1);
            suit();
            pg.setValue(100);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        try {
            Desktop.getDesktop().open(new File(path));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser r=new JFileChooser();
            r.setCurrentDirectory(r.getFileSystemView().getHomeDirectory());
            r.setFileSelectionMode(JFileChooser.FILES_ONLY);
            r.addChoosableFileFilter(new FileNameExtensionFilter("Images","png","jpg"));
            r.setAcceptAllFileFilterUsed(true);
            int result = r.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                pg.setValue(0);
                pg.setValue(10);
                generate_pdf(r.getSelectedFile().getAbsolutePath());
                pg.setValue(100);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!Nom.getText().equals("") && !Nom.getText().equals("") && !Nom.getText().equals("")){
            pg.setValue(1);
            switch(type_d.getSelectedIndex()){
                case 0:
                    codebar(Code3.getText());
                    pg.setValue(50);
                    add_toimage("B"+Code3.getText());
                    pg.setValue(100);
                    break;
                case 1:
                    generateQRCode(Code3.getText(), 200, 200, path+"/RQ"+Code3.getText()+".png");
                    pg.setValue(50);
                    add_toimage("/RQ"+Code3.getText());
                    pg.setValue(100);
                    break;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Code3;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prix;
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField code;
    private javax.swing.JTextField code1;
    private javax.swing.JTextField code2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> nbr;
    private javax.swing.JProgressBar pg;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> type_c;
    private javax.swing.JComboBox<String> type_d;
    // End of variables declaration//GEN-END:variables
        private String load_param(){
            File f2,f=new File(System.getProperty("user.home"),"Documents");
            f2=new File (f.getAbsoluteFile()+"/Code generator");
            if(!f2.exists())f2.mkdirs();
            return f2.getAbsolutePath();
        }

    private void codebar(String t) {
        File f3=new File (path+"/"+t+".png");
        if (!f3.exists()) {
            try {
                Code128Bean code128 = new Code128Bean();
                code128.setHeight(15f);
                code128.setModuleWidth(0.3);
                code128.setQuietZone(10);
                code128.doQuietZone(true);
                pg.setValue(30);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                BitmapCanvasProvider canvas = new BitmapCanvasProvider(baos, "image/x-png", 400, BufferedImage.TYPE_BYTE_BINARY, false, 0);
                code128.generateBarcode(canvas, t);
                canvas.finish();
                FileOutputStream fos;
                pg.setValue(50);
                fos = new FileOutputStream(path+"/B"+t+".png");
                fos.write(baos.toByteArray());
                fos.flush();
                fos.close();
                pg.setValue(90);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    private void generateQRCode(String text, int width, int height, String filePath){
        try {
            QRCodeWriter writer = new QRCodeWriter();
            BitMatrix matrix = writer.encode(text, BarcodeFormat.QR_CODE, width, height);
            pg.setValue(30);
            Path path1 = FileSystems.getDefault().getPath(filePath);
            MatrixToImageWriter.writeToPath(matrix, "png", path1);
            
            pg.setValue(90);
        } catch (WriterException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void suit() {
        switch(type.getSelectedIndex()){
            case 0:generer_chifre();
                break;
            case 1:generer_letre();
                break;
        }
    }

    private void generer_chifre() {
        int text_size=code2.getText().length(),c1=Integer.parseInt(code2.getText()),c2=Integer.parseInt(code1.getText());
        String s;
        if(c1>c2){
            int tmp=c1;
            c1=c2;
            c2=tmp;
        }
        pg.setValue(20);
        for(int i=c1;i<=c2;i++){
            s=comleter(""+i,text_size);
            if (type_c.getSelectedIndex()==0) {
                codebar(s);
                if (check.isSelected()) generate_pdf(path+"/B"+s+".png");
            }
            else {
                generateQRCode(s, 200, 200, path+"/RQ"+s+".png");
                if (check.isSelected()) generate_pdf( path+"/RQ"+s+".png");
            }
        }
        pg.setValue(99);
    }

    private String comleter(String t, int text_size) {
       if (t.length()==text_size) return t;
       else return comleter("0"+t,text_size);
    }

    private void generer_letre() {
        
    }
    
    private void generate_pdf(String nom){
        Document doc=new Document();
        try {
            //PdfWriter.getInstance(doc, new FileOutputStream(path+"/"+code.getText()+".pdf"));
            PdfWriter.getInstance(doc, new FileOutputStream(nom+".pdf"));
            doc.setMargins(0, 0, 0, 0);
            doc.open();
            Image img = Image.getInstance(nom);
            img.scaleAbsolute(50f, 30f);
            int n=Integer.parseInt((String) nbr.getSelectedItem());
            PdfPTable table = new PdfPTable(n);
            table.getDefaultCell().setBorder(Rectangle.NO_BORDER);
            table.setWidthPercentage(100);
            switch(n){
                case 4:n*=14;
                    break;
                case 5:n*=18;
                    break;
                case 6:n*=21;
                    break;
                case 7:n*=24;
                    break;
                case 8:n*=27;
                    break;
                case 9:n*=30;
                    break;
                case 10:n*=33;
                    break;
            }
            for(int i=0;i<n;i++){
                table.addCell(img);
            }
            doc.add(table);
            doc.addTitle("FACTUR");
            doc.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void add_toimage(String t){
        try {
            pg.setValue(50);
            ImageIcon img1=new ImageIcon(path+"/"+t+".png");
            BufferedImage buf = null;
            int w1 = img1.getImage().getWidth(null);
            int h1 = img1.getImage().getHeight(null);
            buf = new BufferedImage(w1, h1+100, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2 = buf.createGraphics();
            g2.setBackground(Color.white);
            g2.fillRect(0, 0, w1, h1+100);
            g2.setColor(Color.BLACK);
            g2.setFont(new Font("Vardana Black", Font.PLAIN, 40));
            g2.drawString(Nom.getText(), 100, 45);
            g2.drawImage(img1.getImage(), 0, 50, null);
            g2.drawString(Prix.getText()+" DA",100, 70+h1);
            ImageIO.write(buf, "png", new File(path+"/B_"+t+".png"));
            pg.setValue(80);
            if (check.isSelected()) generate_pdf(path+"/B_"+t+".png");
            pg.setValue(90);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
